export type Trailing='yes'|'partial'|'emulated'|'unknown'|'no';
export type Priority='core'|'strong'|'optional'|'enterprise';
export interface DataProvider{ id:string; name:string; category:string; assets:string[]; formats:string[]; free:string; paid:string; realtime:string; bestFor:string; limits:string; url:string; priority:Priority; }
export interface BrokerApi{ id:string; name:string; region:string; assets:string[]; api:string; autoTrading:boolean; trailing:Trailing; sandbox:string; pricing:string; bestFor:string; limits:string; setup:string; url:string; status:'preview'|'paper'|'local'|'planned'; }
export interface StrategyMethod{ id:string; name:string; family:string; signals:string[]; data:string[]; horizon:'intraday'|'swing'|'long'|'multi'; automation:'low'|'medium'|'high'; risk:string; }
export const marketDataProviders:DataProvider[]=[
{id:'alpha-vantage',name:'Alpha Vantage',category:'株価/FX/暗号資産/指標/ニュース',assets:['US株','ETF','FX','crypto','macro'],formats:['JSON','CSV','Excel','MCP'],free:'無料枠あり。多くは25 req/day目安',paid:'Premium $49.99/月〜',realtime:'上位プランで米国リアルタイム/高頻度',bestFor:'最初の横断データ源',limits:'無料枠は本番には少ない',url:'https://www.alphavantage.co/',priority:'core'},
{id:'finnhub',name:'Finnhub',category:'株価/財務/ニュース',assets:['US株','海外株','FX','crypto'],formats:['JSON','WebSocket'],free:'無料プランあり',paid:'有料は月額$49.99前後〜',realtime:'リアルタイム/WebSocketあり',bestFor:'株価・企業情報・ニュース統合',limits:'商用/国際市場は契約確認',url:'https://finnhub.io/pricing',priority:'strong'},
{id:'fmp',name:'Financial Modeling Prep',category:'決算書/財務/スクリーナー',assets:['US株','海外株','ETF','FX','crypto'],formats:['JSON','CSV'],free:'無料枠あり',paid:'$19/月、$49/月、$99/月など',realtime:'上位で高頻度',bestFor:'AI決算分析',limits:'再配信/商用は契約確認',url:'https://site.financialmodelingprep.com/pricing-plans',priority:'core'},
{id:'massive',name:'Massive / Polygon',category:'米国株/OP/FX/crypto',assets:['US株','options','FX','crypto'],formats:['JSON','CSV','WebSocket'],free:'Basic無料枠あり',paid:'Stocks Starter $29/月〜',realtime:'プランによりリアルタイム',bestFor:'実運用に近い米国マーケットデータ',limits:'取引所データ権利に注意',url:'https://massive.com/pricing',priority:'core'},
{id:'twelve-data',name:'Twelve Data',category:'グローバル株価/テクニカル',assets:['海外株','ETF','FX','crypto','indices'],formats:['JSON','CSV','WebSocket'],free:'Basic無料枠',paid:'Grow $29/月〜',realtime:'市場により遅延/リアルタイム',bestFor:'多国籍銘柄と指標',limits:'クレジット消費管理が必要',url:'https://twelvedata.com/pricing',priority:'strong'},
{id:'tiingo',name:'Tiingo',category:'EOD/ニュース/crypto',assets:['US株','ETF','crypto','news'],formats:['JSON'],free:'Starter無料枠',paid:'Power $30/月など',realtime:'IEXイントラデイ等',bestFor:'品質重視のEOD',limits:'超高速用途ではない',url:'https://www.tiingo.com/pricing',priority:'strong'},
{id:'eodhd',name:'EODHD',category:'EOD/財務/ニュース',assets:['海外株','ETF','FX','crypto','options'],formats:['JSON','CSV','WebSocket'],free:'無料プランあり',paid:'$19.99/月〜',realtime:'Live/Delayed/WebSocket',bestFor:'世界株の保存分析',limits:'オプション/リアルタイムは追加',url:'https://eodhd.com/',priority:'strong'},
{id:'sec',name:'SEC EDGAR APIs',category:'米国開示/XBRL',assets:['US株'],formats:['JSON','XBRL','bulk'],free:'無料',paid:'無料',realtime:'提出後取得',bestFor:'10-K/10-Q/8-K原典分析',limits:'User-AgentとXBRL処理が必要',url:'https://www.sec.gov/search-filings/edgar-application-programming-interfaces',priority:'core'},
{id:'jquants',name:'J-Quants API',category:'日本株/JPX公式',assets:['日本株','指数','財務','信用','空売り'],formats:['JSON','CSV'],free:'Free ¥0',paid:'Light ¥1,650/月、Standard ¥3,300/月、TDnet add-on ¥11,000/月など',realtime:'主に履歴/日次。TDnetは遅延あり',bestFor:'日本株バックテスト/財務分析',limits:'プラン別に取得範囲制限',url:'https://jpx-jquants.com/',priority:'core'},
{id:'edinet',name:'EDINET API',category:'日本有報/XBRL',assets:['日本上場企業','ファンド'],formats:['JSON','XBRL','ZIP','PDF'],free:'無料',paid:'無料',realtime:'開示文書取得',bestFor:'日本語有報AI解析',limits:'XBRL名寄せが必要',url:'https://disclosure2dl.edinet-fsa.go.jp/guide/static/disclosure/WZEK0110.html',priority:'core'},
{id:'tdnet',name:'JPX TDnet API / J-Quants TDnet',category:'日本適時開示',assets:['日本株'],formats:['API','PDF','XBRL'],free:'原則有料',paid:'J-Quants add-on ¥11,000/月、TDnet APIは個別契約',realtime:'適時開示配信/遅延あり',bestFor:'決算短信/IRイベント',limits:'利用権利と再配信条件注意',url:'https://www.jpx.co.jp/english/markets/paid-info-listing/tdnet/02.html',priority:'strong'},
{id:'fred',name:'FRED API',category:'米国マクロ',assets:['macro','rates','inflation','labor'],formats:['JSON','XML'],free:'無料APIキー',paid:'無料',realtime:'経済指標更新に追随',bestFor:'金利/CPI/雇用レジーム',limits:'指標改定履歴に注意',url:'https://fred.stlouisfed.org/docs/api/fred/overview.html',priority:'core'},
{id:'worldbank',name:'World Bank Indicators',category:'国際マクロ',assets:['macro','country'],formats:['JSON','XML'],free:'無料',paid:'無料',realtime:'低頻度',bestFor:'国別配分/長期分析',limits:'短期売買向けではない',url:'https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation',priority:'optional'},
{id:'oecd',name:'OECD SDMX API',category:'先進国統計',assets:['macro','country'],formats:['SDMX','JSON','CSV'],free:'無料',paid:'無料',realtime:'低頻度',bestFor:'景気/金利/インフレ分析',limits:'SDMXキー理解が必要',url:'https://www.oecd.org/en/data/insights/data-explainers/2024/09/api.html',priority:'optional'},
{id:'coingecko',name:'CoinGecko API',category:'暗号資産データ',assets:['crypto','DEX','NFT'],formats:['JSON'],free:'Demo無料枠',paid:'$35/月〜',realtime:'価格/市場データ',bestFor:'crypto横断スクリーニング',limits:'売買は取引所APIが必要',url:'https://www.coingecko.com/en/api/pricing',priority:'core'},
{id:'coinmarketcap',name:'CoinMarketCap API',category:'暗号資産データ',assets:['crypto','DEX'],formats:['JSON'],free:'Basic無料',paid:'Hobbyist $29/月、Startup $79/月、Standard $299/月など',realtime:'高頻度更新はプラン依存',bestFor:'時価総額/分類/発見',limits:'履歴/商用は上位',url:'https://coinmarketcap.com/api/pricing/',priority:'strong'},
{id:'cryptocompare',name:'CryptoCompare',category:'crypto価格/ニュース',assets:['crypto','exchange','news'],formats:['JSON','WebSocket'],free:'無料キーあり',paid:'商用/高負荷は有料',realtime:'ストリーミングあり',bestFor:'cryptoニュースと価格',limits:'料金は用途ごと確認',url:'https://www.cryptocompare.com/coins/guides/how-to-use-our-api/',priority:'optional'},
{id:'ccxt',name:'CCXT',category:'暗号資産取引所統一ライブラリ',assets:['crypto exchanges'],formats:['JS','TS','Python','PHP','Go','C#'],free:'OSS無料',paid:'CCXT Pro等は有料の場合あり',realtime:'REST/取引所依存',bestFor:'複数取引所の売買統一',limits:'注文型差異のadapter検証必須',url:'https://github.com/ccxt/ccxt',priority:'core'},
{id:'newsapi',name:'News API',category:'一般ニュース',assets:['news','sentiment'],formats:['JSON'],free:'Developer $0、100 req/day',paid:'Business $449/月など',realtime:'無料は制限あり',bestFor:'ニュース収集/AI要約',limits:'無料商用不可等に注意',url:'https://newsapi.org/pricing',priority:'optional'},
{id:'gdelt',name:'GDELT',category:'グローバルニュース/イベント',assets:['news','geopolitics','sentiment'],formats:['JSON','CSV','BigQuery'],free:'無料',paid:'無料。BigQuery費用は別',realtime:'ほぼリアルタイム',bestFor:'地政学/テーマ検知',limits:'ノイズ除去が重要',url:'https://www.gdeltproject.org/data.html',priority:'strong'},
{id:'benzinga',name:'Benzinga APIs',category:'金融ニュース/決算/アナリスト',assets:['US株','crypto','news'],formats:['API','FTP','TCP','JSON'],free:'サンプル/キー案内あり',paid:'法人向け問い合わせ中心',realtime:'市場向けニュース',bestFor:'イベント駆動',limits:'公開価格は限定的',url:'https://www.benzinga.com/apis/',priority:'enterprise'},
{id:'nasdaq-data-link',name:'Nasdaq Data Link',category:'データマーケットプレイス',assets:['equities','futures','macro','alternative'],formats:['API','Python','R','Excel'],free:'無料データセットあり',paid:'データセット別',realtime:'セット依存',bestFor:'代替/専門データ',limits:'権利管理が必要',url:'https://docs.data.nasdaq.com/',priority:'optional'},
{id:'yfinance',name:'Yahoo Finance / yfinance',category:'非公式データ',assets:['海外株','ETF','FX','crypto'],formats:['Python','DataFrame'],free:'無料',paid:'なし',realtime:'遅延/仕様変更リスク',bestFor:'プロトタイプ',limits:'本番/商用は非推奨',url:'https://github.com/ranaroussi/yfinance',priority:'optional'}
];
export const brokerApis:BrokerApi[]=[
{id:'ibkr',name:'Interactive Brokers',region:'Global',assets:['stocks','options','futures','FX','bonds'],api:'TWS API / IB Gateway / Client Portal',autoTrading:true,trailing:'yes',sandbox:'Paper Trading',pricing:'手数料/市場データは地域商品別',bestFor:'本格マルチアセット',limits:'Gateway/TWS常駐が必要',setup:'PaperでAPI許可後Liveへ',url:'https://www.interactivebrokers.com/campus/ibkr-api-page/trader-workstation-api/',status:'preview'},
{id:'alpaca',name:'Alpaca Markets',region:'US/support',assets:['stocks','ETF','options','crypto'],api:'REST/WebSocket/SDK',autoTrading:true,trailing:'yes',sandbox:'Paper Trading API',pricing:'データ/口座条件依存',bestFor:'API-first米国株/crypto',limits:'居住国/PDT/市場データ注意',setup:'Paper keys→Live keys',url:'https://docs.alpaca.markets/us/docs/orders-at-alpaca',status:'preview'},
{id:'tradestation',name:'TradeStation',region:'US',assets:['stocks','options','futures','crypto'],api:'REST/EasyLanguage',autoTrading:true,trailing:'yes',sandbox:'Simulated',pricing:'商品別',bestFor:'米国株/先物/OP',limits:'OAuth/商品別仕様確認',setup:'Developer登録→Sim検証',url:'https://api.tradestation.com/docs/',status:'preview'},
{id:'schwab',name:'Charles Schwab Trader API',region:'US',assets:['stocks','ETF','options'],api:'REST/OAuth',autoTrading:true,trailing:'partial',sandbox:'Developer app',pricing:'口座条件依存',bestFor:'米国株/OP',limits:'高度注文は実機確認',setup:'Developer Portal登録',url:'https://developer.schwab.com/products/trader-api--individual',status:'planned'},
{id:'tradier',name:'Tradier',region:'US',assets:['stocks','ETF','options'],api:'REST',autoTrading:true,trailing:'emulated',sandbox:'Sandbox',pricing:'口座/データ条件依存',bestFor:'簡潔な米国株/OP注文',limits:'trailingは自前監視',setup:'Sandboxで注文検証',url:'https://docs.tradier.com/docs/orders',status:'preview'},
{id:'tastytrade',name:'tastytrade Open API',region:'US',assets:['stocks','ETF','options','futures'],api:'REST/Streamer',autoTrading:true,trailing:'unknown',sandbox:'Sandbox',pricing:'口座条件依存',bestFor:'OP中心',limits:'trailing要確認',setup:'Sandbox検証',url:'https://tastytrade.com/api/',status:'planned'},
{id:'oanda',name:'OANDA v20',region:'Global FX',assets:['FX','CFD'],api:'REST/Streaming',autoTrading:true,trailing:'yes',sandbox:'Practice',pricing:'スプレッド依存',bestFor:'FX自動売買',limits:'地域/レバレッジ注意',setup:'Practice token→Live',url:'https://developer.oanda.com/rest-live-v20/order-df/',status:'preview'},
{id:'ig',name:'IG API',region:'Global',assets:['FX','CFD','indices','shares'],api:'REST/Streaming',autoTrading:true,trailing:'partial',sandbox:'Demo',pricing:'スプレッド/データ依存',bestFor:'CFD/FX',limits:'地域商品差あり',setup:'Demo API key',url:'https://labs.ig.com/',status:'planned'},
{id:'kabu-station',name:'三菱UFJ eスマート証券 kabuステーションAPI',region:'Japan',assets:['日本株','信用','先物','OP'],api:'Local REST/PUSH/Excel',autoTrading:true,trailing:'partial',sandbox:'ローカルツール起動',pricing:'API原則無料/手数料別',bestFor:'日本株REST自動売買',limits:'PCとkabuステーション常駐',setup:'APIパスワード/localhost',url:'https://kabu.com/company/lp/lp90.html',status:'preview'},
{id:'tachibana',name:'立花証券 e支店 API',region:'Japan',assets:['日本株','信用'],api:'REST',autoTrading:true,trailing:'emulated',sandbox:'本番口座/少額検証',pricing:'API無料案内/手数料別',bestFor:'日本株サーバー連携',limits:'trailingは自前',setup:'口座/API利用設定',url:'https://www.e-shiten.jp/api/',status:'preview'},
{id:'rakuten-rss',name:'楽天証券 MarketSpeed II RSS',region:'Japan',assets:['日本株','先物','OP'],api:'Excel RSS/VBA',autoTrading:true,trailing:'partial',sandbox:'Windows/Excel',pricing:'ツール条件/手数料別',bestFor:'Excel自動売買',limits:'クラウド直結ではない',setup:'RSSアドイン/VBA',url:'https://marketspeed.jp/ms2_rss/',status:'local'},
{id:'sbi-neotrade',name:'SBIネオトレード ネオトレAPI for Excel',region:'Japan',assets:['日本株','指数','FX rates'],api:'Excel/VBA',autoTrading:true,trailing:'emulated',sandbox:'Windows/Excel',pricing:'無料提供/手数料別',bestFor:'Excel完結',limits:'VBA監視が必要',setup:'利用申請/アドイン',url:'https://www.sbineotrade.jp/tool/api/',status:'local'},
{id:'moomoo-jp',name:'moomoo Japan OpenAPI / API Skill',region:'Japan/US',assets:['US stocks'],api:'OpenAPI/API Skill',autoTrading:true,trailing:'unknown',sandbox:'デモ→本番',pricing:'口座条件依存',bestFor:'AIエージェント連携',limits:'trailing要検証',setup:'OpenAPI利用条件確認',url:'https://www.moomoo.com/jp/newsroom/moomoo-api-skill',status:'planned'},
{id:'gmo-fx',name:'GMOコイン 外国為替FX API',region:'Japan',assets:['FX'],api:'Public/Private API',autoTrading:true,trailing:'emulated',sandbox:'条件確認',pricing:'API約定手数料の場合あり/無料トライアル案内',bestFor:'国内FX API',limits:'trailingは監視実装',setup:'FX口座/APIキー',url:'https://coin.z.com/jp/corp/product/info/fx/api/',status:'preview'},
{id:'binance',name:'Binance',region:'Global/support',assets:['crypto spot','futures','options'],api:'REST/WebSocket/FIX/Testnet',autoTrading:true,trailing:'yes',sandbox:'Spot/Futures testnet',pricing:'取引手数料/VIP依存',bestFor:'crypto高頻度',limits:'地域/権限/清算注意',setup:'Testnet/IP制限',url:'https://developers.binance.com/docs/binance-spot-api-docs/faqs/trailing-stop-faq',status:'preview'},
{id:'bybit',name:'Bybit',region:'Global/support',assets:['crypto spot','perp','futures','options'],api:'REST/WebSocket/Testnet',autoTrading:true,trailing:'yes',sandbox:'Testnet',pricing:'手数料/VIP依存',bestFor:'cryptoデリバティブ',limits:'レバレッジ/地域注意',setup:'Set Trading Stop検証',url:'https://bybit-exchange.github.io/docs/v5/position/trading-stop',status:'preview'},
{id:'okx',name:'OKX',region:'Global/support',assets:['crypto spot','margin','futures','options'],api:'REST/WebSocket/Demo',autoTrading:true,trailing:'yes',sandbox:'Demo trading',pricing:'手数料/VIP依存',bestFor:'高度注文/アルゴ',limits:'証拠金設定注意',setup:'Demoでmove_order_stop検証',url:'https://www.okx.com/docs-v5/en/',status:'preview'},
{id:'kraken',name:'Kraken',region:'Global/support',assets:['crypto spot','margin','futures'],api:'REST/WebSocket/FIX',autoTrading:true,trailing:'yes',sandbox:'権限制限キー/商品別',pricing:'取引量依存',bestFor:'堅めのcrypto API',limits:'relative price/注文数注意',setup:'trailing-stop小口検証',url:'https://docs.kraken.com/api/docs/rest-api/add-order',status:'preview'},
{id:'coinbase',name:'Coinbase Advanced Trade API',region:'US/support',assets:['crypto spot'],api:'REST/WebSocket',autoTrading:true,trailing:'unknown',sandbox:'API世代で差',pricing:'手数料/地域依存',bestFor:'米国系crypto',limits:'trailing要確認',setup:'権限最小化',url:'https://docs.cdp.coinbase.com/coinbase-app/advanced-trade-apis/overview',status:'planned'}
];
export const strategyLibrary:StrategyMethod[]=[
{id:'sma',name:'SMA/EMAトレンド',family:'テクニカル',signals:['MAクロス','ADX','高値更新'],data:['OHLCV'],horizon:'swing',automation:'high',risk:'レンジでダマシ'},
{id:'rsi',name:'RSI逆張り',family:'テクニカル',signals:['RSI<30','RSI>70'],data:['OHLCV'],horizon:'swing',automation:'high',risk:'強トレンドで損失'},
{id:'breakout',name:'高値ブレイクアウト',family:'モメンタム',signals:['N日高値','出来高','ATR'],data:['OHLCV'],horizon:'swing',automation:'high',risk:'フェイクブレイク'},
{id:'vol-target',name:'ボラティリティターゲット',family:'リスク管理',signals:['実現ボラ','ATR','DD'],data:['OHLCV','portfolio'],horizon:'multi',automation:'high',risk:'急変時に遅れる'},
{id:'quality-value',name:'クオリティ・バリュー',family:'ファンダメンタル',signals:['ROIC','PER','FCF'],data:['財務','価格'],horizon:'long',automation:'medium',risk:'バリュートラップ'},
{id:'growth-revision',name:'成長/上方修正',family:'ファンダメンタル',signals:['売上成長','EPS','ガイダンス'],data:['財務','決算','news'],horizon:'long',automation:'medium',risk:'期待先行'},
{id:'earnings-drift',name:'決算後ドリフト',family:'イベント',signals:['決算サプライズ','出来高','gap'],data:['決算','価格','news'],horizon:'swing',automation:'medium',risk:'発表時刻/流動性'},
{id:'news-ai',name:'ニュース/AIセンチメント',family:'AI',signals:['極性','報道量','異常トピック'],data:['news','prices','NLP'],horizon:'intraday',automation:'medium',risk:'ノイズ/誤報'},
{id:'pairs',name:'ペアトレード',family:'クオンツ',signals:['Zスコア','相関','共和分'],data:['prices'],horizon:'swing',automation:'medium',risk:'相関崩壊'},
{id:'sector',name:'セクターローテーション',family:'マクロ',signals:['相対強度','金利','景気'],data:['ETF','macro'],horizon:'long',automation:'medium',risk:'局面判定遅れ'},
{id:'crypto-momo',name:'暗号資産モメンタム',family:'crypto',signals:['24h/7d momentum','volume','funding'],data:['crypto','derivatives'],horizon:'intraday',automation:'high',risk:'清算/取引所リスク'},
{id:'fx-carry',name:'FXキャリー+トレンド',family:'FX',signals:['金利差','MA','ボラ'],data:['FX','rates','macro'],horizon:'swing',automation:'medium',risk:'介入/急変'}
];
export const researchMetadata={lastVerifiedDate:'2026-05-31',providerCount:marketDataProviders.length,brokerCount:brokerApis.length,strategyCount:strategyLibrary.length,workbookFileName:'investing_api_research.xlsx'};
