import{brokerApis,marketDataProviders,strategyLibrary,type BrokerApi,type DataProvider,type StrategyMethod}from'./research';
export type Risk='low'|'medium'|'high'; export type Asset='equity'|'japan-equity'|'crypto'|'fx'|'multi'; export type Horizon='intraday'|'swing'|'long'|'multi'; export type Budget='free'|'low-cost'|'paid'|'enterprise';
export interface StrategyProfile{riskTolerance:Risk;assetClass:Asset;horizon:Horizon;dataBudget:Budget;prefersFundamental:boolean;prefersTechnical:boolean;prefersNews:boolean;}
export const DEFAULT_STRATEGY_PROFILE:StrategyProfile={riskTolerance:'medium',assetClass:'equity',horizon:'swing',dataBudget:'low-cost',prefersFundamental:true,prefersTechnical:true,prefersNews:true};
function has(xs:string[],q:string[]){const s=xs.join(' ').toLowerCase();return q.some(x=>s.includes(x.toLowerCase()));}
function scoreStrategy(s:StrategyMethod,p:StrategyProfile){let n=0;if(s.horizon===p.horizon||s.horizon==='multi'||p.horizon==='multi')n+=3;if(p.prefersTechnical&&['テクニカル','モメンタム'].some(x=>s.family.includes(x)))n+=3;if(p.prefersFundamental&&s.family.includes('ファンダ'))n+=3;if(p.prefersNews&&(['AI','イベント'].some(x=>s.family.includes(x))||s.data.includes('news')))n+=2;if(p.assetClass==='crypto'&&s.family==='crypto')n+=4;if(p.assetClass==='fx'&&s.family==='FX')n+=4;if(p.riskTolerance==='low'&&['vol-target','sector','quality-value'].includes(s.id))n+=3;if(p.riskTolerance==='high'&&['breakout','crypto-momo','news-ai'].includes(s.id))n+=2;return n;}
function providerAsset(d:DataProvider,a:Asset){if(a==='multi')return true;if(a==='crypto')return has(d.assets,['crypto','暗号']);if(a==='fx')return has(d.assets,['FX','macro','rates']);if(a==='japan-equity')return has(d.assets,['日本','Japan']);return has(d.assets,['US','海外','株','ETF','equities']);}
function brokerAsset(b:BrokerApi,a:Asset){if(a==='multi')return true;if(a==='crypto')return has(b.assets,['crypto']);if(a==='fx')return has(b.assets,['FX','CFD']);if(a==='japan-equity')return has(b.assets,['日本']);return has(b.assets,['stocks','ETF','options','株']);}
function budget(d:DataProvider,b:Budget){if(b==='enterprise')return true;if(b==='paid')return d.priority!=='enterprise';if(b==='low-cost')return d.priority==='core'||d.priority==='strong'||d.free.includes('無料');return d.free.includes('無料')||d.free.includes('Free');}
export function recommendStrategy(profile:StrategyProfile=DEFAULT_STRATEGY_PROFILE){const strategies=strategyLibrary.map(s=>({s,n:scoreStrategy(s,profile)})).sort((a,b)=>b.n-a.n).slice(0,5).map(x=>x.s);const dataProviders=marketDataProviders.filter(d=>providerAsset(d,profile.assetClass)&&budget(d,profile.dataBudget)).slice(0,8);const order={yes:4,partial:3,emulated:2,unknown:1,no:0};const brokers=brokerApis.filter(b=>brokerAsset(b,profile.assetClass)).sort((a,b)=>order[b.trailing]-order[a.trailing]).slice(0,6);const risk=profile.riskTolerance==='low'?{maxPositionPct:.05,stopLossPct:.04,trailingStopPct:.06,maxDailyLossPct:.01,paperDays:60}:profile.riskTolerance==='high'?{maxPositionPct:.15,stopLossPct:.1,trailingStopPct:.14,maxDailyLossPct:.04,paperDays:20}:{maxPositionPct:.1,stopLossPct:.07,trailingStopPct:.1,maxDailyLossPct:.02,paperDays:30};return{profile,strategies,dataProviders,brokers,risk,guardrails:['Paper tradingを既定値にする','LIVE_TRADING_ENABLED=trueまで実発注を拒否する','最大発注額/日次損失/ポジション比率を発注前検証する','trailing未対応ブローカーは監視ループでエミュレーションする']};}
